// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout from "../components/Layout.js";

function Index(Props) {
  return React.createElement(Layout.make, {
              children: "Hello Gatsby"
            });
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
