// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as CamlinternalOO from "bs-platform/lib/es6/camlinternalOO.js";

var class_tables = /* Cons */[
  undefined,
  undefined,
  undefined
];

function Layout(Props) {
  Props.children;
  Props.colorMode;
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env = CamlinternalOO.new_variable($$class, "");
    var env_init = function (env$1) {
      var self = CamlinternalOO.create_object_opt(undefined, $$class);
      self[env] = env$1;
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], undefined);
}

var make = Layout;

export {
  make ,
  
}
/* No side effect */
