// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as MakeStyles from "../MakeStyles.js";

function styles(theme) {
  var appContainer = function (props) {
    return MakeStyles.css(/* :: */[
                MakeStyles.backgroundColor(props ? theme.background.dark : theme.background.light),
                /* :: */[
                  MakeStyles.width(MakeStyles.vw(100)),
                  /* :: */[
                    MakeStyles.height(MakeStyles.vh(100)),
                    /* [] */0
                  ]
                ]
              ]);
  };
  return MakeStyles.create(/* :: */[
              /* tuple */[
                "appContainer",
                appContainer
              ],
              /* [] */0
            ]);
}

var useStyles = MakeStyles.makeThemeStyles(styles);

function Layout(Props) {
  var children = Props.children;
  var colorModeOpt = Props.colorMode;
  var colorMode = colorModeOpt !== undefined ? colorModeOpt : /* Dark */1;
  var classes = useStyles(colorMode);
  return React.createElement("div", {
              className: Curry._1(classes, "appContainer")
            }, React.createElement("main", undefined, children));
}

var make = Layout;

export {
  styles ,
  useStyles ,
  make ,
  
}
/* useStyles Not a pure module */
