// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function iterChildren(mapper, node) {
  return $$Array.iter((function (node) {
                Curry._1(mapper, node);
                
              }), node.childNodes);
}

function useDomRef(ref) {
  return Belt_Option.getExn(Caml_option.nullable_to_opt(ref.current));
}

export {
  iterChildren ,
  useDomRef ,
  
}
/* No side effect */
