// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Core from "@material-ui/core";

var colors = {
  black: "#0A100D",
  white: "#F2F4F3",
  gray: "#40434E",
  lightPink: "#A39BA8",
  pink: "#C297B8",
  babyYoda: {
    green: "#B1CDAF",
    brown: "#9B8B7B",
    lightBrown: "#CECAAC"
  }
};

var theme_background = {
  dark: "#0A100D",
  light: "#F2F4F3"
};

var theme_typography = {
  h1: {
    fontSize: 36,
    fontWeight: 700
  }
};

var theme = {
  colors: colors,
  background: theme_background,
  spacer: 8,
  typography: theme_typography
};

var CustomTheme = {
  colors: colors,
  theme: theme
};

var theme$1 = Core.createMuiTheme(theme);

var Theme = {
  CustomTheme: CustomTheme,
  theme: theme$1
};

var CssBaseline = { };

var MuiThemeProvider = { };

export {
  Theme ,
  CssBaseline ,
  MuiThemeProvider ,
  
}
/* theme Not a pure module */
