// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as CamlinternalOO from "bs-platform/lib/es6/camlinternalOO.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";
import * as Styles from "@material-ui/styles";

function clsx(classNames) {
  return List.fold_left((function (classes, cls) {
                return "" + (String(classes) + (" " + (String(cls) + "")));
              }), "", classNames);
}

function toFloat(prim) {
  return prim;
}

function toInt(prim) {
  return prim | 0;
}

function toStr(prim) {
  return String(prim);
}

function vw($$int) {
  return String($$int) + "vw";
}

function vh($$int) {
  return String($$int) + "vh";
}

function px($$int) {
  return String($$int) + "px";
}

function pct($$int) {
  return String($$int) + "%";
}

function deg($$int) {
  return String($$int) + "deg";
}

function ms($$int) {
  return String($$int) + "ms";
}

function width(str) {
  return /* tuple */[
          "width",
          str
        ];
}

function height(str) {
  return /* tuple */[
          "height",
          str
        ];
}

function overflow(str) {
  return /* tuple */[
          "overflow",
          str
        ];
}

function flexDirection(str) {
  return /* tuple */[
          "flex-direction",
          str
        ];
}

function padding(pad) {
  var getPaddingStr = function (str, p) {
    return str + (", " + p);
  };
  var paddingStr = List.fold_left(getPaddingStr, "", pad);
  return /* tuple */[
          "padding",
          paddingStr
        ];
}

function transition(str) {
  return /* tuple */[
          "transition",
          str
        ];
}

function transform(str) {
  return /* tuple */[
          "transfrom",
          str
        ];
}

function zIndex(index) {
  return /* tuple */[
          "z-index",
          String(index)
        ];
}

function margin(marg) {
  var getMarginStr = function (str, m) {
    return str + (", " + m);
  };
  var marginStr = List.fold_left(getMarginStr, "", marg);
  return /* tuple */[
          "margin",
          marginStr
        ];
}

function opacity(num) {
  return /* tuple */[
          "opacity",
          num.toString()
        ];
}

function textAlign(str) {
  return /* tuple */[
          "text-align",
          str
        ];
}

function lineHeight(str) {
  return /* tuple */[
          "line-height",
          str
        ];
}

function fontSize(str) {
  return /* tuple */[
          "font-size",
          str
        ];
}

function textDecoration(str) {
  return /* tuple */[
          "text-decoration",
          str
        ];
}

function nthChild(child, dict) {
  var child$1 = String(child);
  return /* tuple */[
          "&:nth-child(" + (String(child$1) + ")"),
          dict
        ];
}

function $$var(str, dict) {
  return /* tuple */[
          "&$" + str,
          dict
        ];
}

function hover(dict) {
  return /* tuple */[
          "&:hover",
          dict
        ];
}

function rotate(str) {
  return "rotate(" + (String(str) + ")");
}

function translateY(str) {
  return "translateY(" + (String(str) + ")");
}

function translate(x, y) {
  return "translate(" + (String(x) + (", " + (String(y) + ")")));
}

function important(str) {
  return str + " !important";
}

function keyframes(name, frames) {
  var formatFrames = function (dict, param) {
    dict[String(param[0]) + "%"] = param[1];
    return dict;
  };
  var keyframe = List.fold_left(formatFrames, { }, frames);
  return /* tuple */[
          "@keyframes " + (String(name) + ""),
          keyframe
        ];
}

var css = Js_dict.fromList;

var create = Js_dict.fromList;

function getClassName(classes, key) {
  var className = Js_dict.get(classes, key);
  if (className !== undefined) {
    return className;
  } else {
    return "";
  }
}

function useStyles(muiUseStyles, props) {
  var partial_arg = props !== undefined ? Curry._1(muiUseStyles, Caml_option.valFromOption(props)) : Curry._1(muiUseStyles, "");
  return (function (param) {
      return getClassName(partial_arg, param);
    });
}

function makeGlobalStyles(styles) {
  var styleDict = { };
  styleDict["@global"] = styles;
  var partial_arg = Styles.makeStyles(styleDict);
  return (function (param) {
      return useStyles(partial_arg, param);
    });
}

function makeStyles(styles) {
  var partial_arg = Styles.makeStyles(styles);
  return (function (param) {
      return useStyles(partial_arg, param);
    });
}

function makeThemeStyles(styleFunc) {
  var partial_arg = Styles.makeStyles(styleFunc);
  return (function (param) {
      return useStyles(partial_arg, param);
    });
}

var auto = "auto";

var initial = "initial";

var inherit_ = "inherit";

var none = "none";

var unset = "unset";

function getLength(length) {
  switch (length.tag | 0) {
    case /* Cm */0 :
        return String(length[0]) + "cm";
    case /* Mm */1 :
        return String(length[0]) + "mm";
    case /* In */2 :
        return String(length[0]) + "in";
    case /* Px */3 :
        return String(length[0]) + "px";
    case /* Pt */4 :
        return String(length[0]) + "pt";
    case /* Pc */5 :
        return String(length[0]) + "pc";
    case /* Em */6 :
        return String(length[0]) + "em";
    case /* Ex */7 :
        return String(length[0]) + "ex";
    case /* Ch */8 :
        return String(length[0]) + "ch";
    case /* Rem */9 :
        return String(length[0]) + "rem";
    case /* Vw */10 :
        return String(length[0]) + "vw";
    case /* Vh */11 :
        return String(length[0]) + "vh";
    case /* Vmin */12 :
        return String(length[0]) + "vmin";
    case /* Vmax */13 :
        return String(length[0]) + "vmax";
    case /* Pct */14 :
        return String(length[0]) + "%";
    
  }
}

var Length = {
  getLength: getLength
};

function timing(opt) {
  if (typeof opt === "number") {
    switch (opt) {
      case /* Linear */0 :
          return "linear";
      case /* Ease */1 :
          return "ease";
      case /* EaseIn */2 :
          return "ease-in";
      case /* EaseOut */3 :
          return "ease-out";
      case /* EaseInOut */4 :
          return "ease-in-out";
      case /* StepStart */5 :
          return "step-start";
      case /* StepEnd */6 :
          return "step-end";
      case /* Initial */7 :
          return initial;
      case /* Inherit */8 :
          return inherit_;
      
    }
  } else {
    switch (opt.tag | 0) {
      case /* Step */0 :
          return "steps(" + (String(opt[0]) + ")");
      case /* Steps */1 :
          var step = opt[1];
          var stepValue = typeof step === "number" ? (
              step !== 0 ? "end" : "start"
            ) : step[0];
          return "steps(" + (String(opt[0]) + (", " + (String(stepValue) + ")")));
      case /* CubicBezier */2 :
          return "cubic-bezier(" + (String(opt[0]) + (", " + (String(opt[1]) + (", " + (String(opt[2]) + (", " + (String(opt[3]) + ")")))))));
      case /* Unsafe_set */3 :
          return opt[0];
      
    }
  }
}

var TimingFunctions = {
  timing: timing
};

function alignContent(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Stretch */0 :
          tmp = "stretch";
          break;
      case /* Center */1 :
          tmp = "center";
          break;
      case /* FlexStart */2 :
          tmp = "flex-start";
          break;
      case /* FlexEnd */3 :
          tmp = "flex-end";
          break;
      case /* SpaceBetween */4 :
          tmp = "space-between";
          break;
      case /* SpaceAround */5 :
          tmp = "space-around";
          break;
      case /* Initial */6 :
          tmp = initial;
          break;
      case /* Inherit */7 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "align-content",
          tmp
        ];
}

function alignItems(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Stretch */0 :
          tmp = "stretch";
          break;
      case /* Center */1 :
          tmp = "center";
          break;
      case /* FlexStart */2 :
          tmp = "flex-start";
          break;
      case /* FlexEnd */3 :
          tmp = "flex-end";
          break;
      case /* Baseline */4 :
          tmp = "baseline";
          break;
      case /* Initial */5 :
          tmp = initial;
          break;
      case /* Inherit */6 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "align-items",
          tmp
        ];
}

function alignSelf(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Auto */0 :
          tmp = "auto";
          break;
      case /* Stretch */1 :
          tmp = "stretch";
          break;
      case /* Center */2 :
          tmp = "center";
          break;
      case /* FlexStart */3 :
          tmp = "flex-start";
          break;
      case /* FlexEnd */4 :
          tmp = "flex-end";
          break;
      case /* Baseline */5 :
          tmp = "baseline";
          break;
      case /* Initial */6 :
          tmp = initial;
          break;
      case /* Inherit */7 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "align-self",
          tmp
        ];
}

var Align = {
  alignContent: alignContent,
  alignItems: alignItems,
  alignSelf: alignSelf
};

function all(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Initial */0 :
          tmp = initial;
          break;
      case /* Inherit */1 :
          tmp = inherit_;
          break;
      case /* Unset */2 :
          tmp = unset;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "all",
          tmp
        ];
}

var All = {
  all: all
};

var Not_valid = Caml_exceptions.create("MuiStyles.Animation.Not_valid");

function _animationTime(opt) {
  if (typeof opt === "number") {
    if (opt === /* Initial */0) {
      return initial;
    } else {
      return inherit_;
    }
  }
  if (opt.tag) {
    return opt[0];
  }
  var str = opt[0];
  if (str.includes("ms") || str.includes("s")) {
    return str;
  }
  throw [
        Not_valid,
        "Time(string) needs to be in seconds or miliseconds"
      ];
}

function animationDelay(opt) {
  return /* tuple */[
          "animation-delay",
          _animationTime(opt)
        ];
}

function animationDirection(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Normal */0 :
          tmp = "normal";
          break;
      case /* Reverse */1 :
          tmp = "reverse";
          break;
      case /* Alternate */2 :
          tmp = "alternate";
          break;
      case /* AlternateReverse */3 :
          tmp = "alternate-reverse";
          break;
      case /* Initial */4 :
          tmp = initial;
          break;
      case /* Inherit */5 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "animation-direction",
          tmp
        ];
}

function animationDuration(opt) {
  return /* tuple */[
          "animation-duration",
          _animationTime(opt)
        ];
}

function animationFillMode(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* None */0 :
          tmp = "none";
          break;
      case /* Forwards */1 :
          tmp = "forwards";
          break;
      case /* Backwards */2 :
          tmp = "backwards";
          break;
      case /* Both */3 :
          tmp = "both";
          break;
      case /* Initial */4 :
          tmp = initial;
          break;
      case /* Inherit */5 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "animation-fill-mode",
          tmp
        ];
}

function animationIterationCount(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Infinite */0 :
          tmp = "infinite";
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt.tag ? opt[0] : String(opt[0]);
  }
  return /* tuple */[
          "animation-iteration-count",
          tmp
        ];
}

function animationName(opt) {
  return /* tuple */[
          "animation-name",
          typeof opt === "number" ? (
              opt !== 0 ? inherit_ : initial
            ) : opt[0]
        ];
}

function animationPlayState(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Paused */0 :
          tmp = "paused";
          break;
      case /* Running */1 :
          tmp = "running";
          break;
      case /* Initial */2 :
          tmp = initial;
          break;
      case /* Inherit */3 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "animation-play-state",
          tmp
        ];
}

function animationTimingFunction(opt) {
  return /* tuple */[
          "animation-timing-function",
          timing(opt)
        ];
}

function animation(opt) {
  var tmp;
  switch (opt.tag | 0) {
    case /* Animation1 */0 :
        tmp = animationName(opt[0])[1];
        break;
    case /* Animation2 */1 :
        var match = animationName(opt[0]);
        var durationValue = _animationTime(opt[1]);
        tmp = "" + (String(match[1]) + (" " + (String(durationValue) + "")));
        break;
    case /* Animation3 */2 :
        var match$1 = animationName(opt[0]);
        var durationValue$1 = _animationTime(opt[1]);
        var timingValue = timing(opt[2]);
        tmp = "" + (String(match$1[1]) + (" " + (String(durationValue$1) + (" " + (String(timingValue) + "")))));
        break;
    case /* Animation4 */3 :
        var match$2 = animationName(opt[0]);
        var durationValue$2 = _animationTime(opt[1]);
        var timingValue$1 = timing(opt[2]);
        var delayValue = _animationTime(opt[3]);
        tmp = "" + (String(match$2[1]) + (" " + (String(durationValue$2) + (" " + (String(timingValue$1) + (" " + (String(delayValue) + "")))))));
        break;
    case /* Animation5 */4 :
        var match$3 = animationName(opt[0]);
        var durationValue$3 = _animationTime(opt[1]);
        var timingValue$2 = timing(opt[2]);
        var delayValue$1 = _animationTime(opt[3]);
        var match$4 = animationIterationCount(opt[4]);
        tmp = "" + (String(match$3[1]) + (" " + (String(durationValue$3) + (" " + (String(timingValue$2) + (" " + (String(delayValue$1) + (" " + (String(match$4[1]) + "")))))))));
        break;
    case /* Animation6 */5 :
        var match$5 = animationName(opt[0]);
        var durationValue$4 = _animationTime(opt[1]);
        var timingValue$3 = timing(opt[2]);
        var delayValue$2 = _animationTime(opt[3]);
        var match$6 = animationDirection(opt[5]);
        var match$7 = animationIterationCount(opt[4]);
        tmp = "" + (String(match$5[1]) + (" " + (String(durationValue$4) + (" " + (String(timingValue$3) + (" " + (String(delayValue$2) + (" " + (String(match$7[1]) + (" " + (String(match$6[1]) + "")))))))))));
        break;
    case /* Animation7 */6 :
        var match$8 = animationName(opt[0]);
        var durationValue$5 = _animationTime(opt[1]);
        var timingValue$4 = timing(opt[2]);
        var delayValue$3 = _animationTime(opt[3]);
        var match$9 = animationIterationCount(opt[4]);
        var match$10 = animationDirection(opt[5]);
        var match$11 = animationFillMode(opt[6]);
        tmp = "" + (String(match$8[1]) + (" " + (String(durationValue$5) + (" " + (String(timingValue$4) + (" " + (String(delayValue$3) + (" " + (String(match$9[1]) + (" " + (String(match$10[1]) + (" " + (String(match$11[1]) + "")))))))))))));
        break;
    case /* Animation8 */7 :
        var match$12 = animationName(opt[0]);
        var durationValue$6 = _animationTime(opt[1]);
        var timingValue$5 = timing(opt[2]);
        var delayValue$4 = _animationTime(opt[3]);
        var match$13 = animationIterationCount(opt[4]);
        var match$14 = animationDirection(opt[5]);
        var match$15 = animationFillMode(opt[6]);
        var match$16 = animationPlayState(opt[7]);
        tmp = "" + (String(match$12[1]) + (" " + (String(durationValue$6) + (" " + (String(timingValue$5) + (" " + (String(delayValue$4) + (" " + (String(match$13[1]) + (" " + (String(match$14[1]) + (" " + (String(match$15[1]) + (" " + (String(match$16[1]) + "")))))))))))))));
        break;
    case /* Unsafe_set */8 :
        tmp = opt[0];
        break;
    
  }
  return /* tuple */[
          "animation",
          tmp
        ];
}

var Animation = {
  Not_valid: Not_valid,
  _animationTime: _animationTime,
  animationDelay: animationDelay,
  animationDirection: animationDirection,
  animationDuration: animationDuration,
  animationFillMode: animationFillMode,
  animationIterationCount: animationIterationCount,
  animationName: animationName,
  animationPlayState: animationPlayState,
  animationTimingFunction: animationTimingFunction,
  animation: animation
};

function backfaceVisibilty(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Visible */0 :
          tmp = "visible";
          break;
      case /* Hidden */1 :
          tmp = "hidden";
          break;
      case /* Initial */2 :
          tmp = initial;
          break;
      case /* Inherit */3 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "backface-visibility",
          tmp
        ];
}

var Backface = {
  backfaceVisibilty: backfaceVisibilty
};

function backgroundAttachment(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Scroll */0 :
          tmp = "scroll";
          break;
      case /* Fixed */1 :
          tmp = "fixed";
          break;
      case /* Local */2 :
          tmp = "local";
          break;
      case /* Initial */3 :
          tmp = initial;
          break;
      case /* Inherit */4 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "background-attachment",
          tmp
        ];
}

function backgroundBlendMode(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Normal */0 :
          tmp = "normal";
          break;
      case /* Multiply */1 :
          tmp = "multiply";
          break;
      case /* Screen */2 :
          tmp = "screen";
          break;
      case /* Overlay */3 :
          tmp = "overlay";
          break;
      case /* Darken */4 :
          tmp = "darken";
          break;
      case /* Lighten */5 :
          tmp = "lighten";
          break;
      case /* ColorDodge */6 :
          tmp = "color-dodge";
          break;
      case /* Saturation */7 :
          tmp = "saturation";
          break;
      case /* Color */8 :
          tmp = "color";
          break;
      case /* Luminosity */9 :
          tmp = "luminosity";
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "background-blend-mode",
          tmp
        ];
}

function _backgroundBoxing(opt) {
  if (typeof opt !== "number") {
    return opt[0];
  }
  switch (opt) {
    case /* BorderBox */0 :
        return "border-box";
    case /* PaddingBox */1 :
        return "padding-box";
    case /* ContentBox */2 :
        return "content-box";
    case /* Initial */3 :
        return initial;
    case /* Inherit */4 :
        return inherit_;
    
  }
}

function backgroundClip(opt) {
  return /* tuple */[
          "background-clip",
          _backgroundBoxing(opt)
        ];
}

function backgroundColor(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Transparent */0 :
          tmp = "transparent";
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "background-color",
          tmp
        ];
}

function backgroundImage(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* None */0 :
          tmp = none;
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    switch (opt.tag | 0) {
      case /* URL */0 :
          tmp = "url(" + (String(opt[0]) + ")");
          break;
      case /* LinearGradient */1 :
          tmp = "linear-gradient(" + (String(opt[0]) + ")");
          break;
      case /* RadialGradient */2 :
          tmp = "radial-gradient(" + (String(opt[0]) + ")");
          break;
      case /* RepeatingLinearGradient */3 :
          tmp = "repeating-linear-gradient(" + (String(opt[0]) + ")");
          break;
      case /* RepeatingRadialGradient */4 :
          tmp = "repeating-radial-gradient(" + (String(opt[0]) + ")");
          break;
      case /* Unsafe_set */5 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "background-image",
          tmp
        ];
}

function backgroundOrigin(opt) {
  return /* tuple */[
          "background-origin",
          _backgroundBoxing(opt)
        ];
}

function backgroundPosition(opt) {
  var tmp;
  if (typeof opt === "number") {
    tmp = opt === /* Initial */0 ? initial : inherit_;
  } else {
    switch (opt.tag | 0) {
      case /* Position */0 :
          var pos2 = opt[1];
          switch (opt[0]) {
            case /* Center */1 :
                switch (pos2) {
                  case /* Bottom */0 :
                      tmp = "center bottom";
                      break;
                  case /* Center */1 :
                  case /* Left */2 :
                  case /* Right */3 :
                      tmp = "center center";
                      break;
                  case /* Top */4 :
                      tmp = "center top";
                      break;
                  
                }
                break;
            case /* Left */2 :
                switch (pos2) {
                  case /* Bottom */0 :
                      tmp = "left bottom";
                      break;
                  case /* Center */1 :
                      tmp = "left enter";
                      break;
                  case /* Left */2 :
                  case /* Right */3 :
                      tmp = "center center";
                      break;
                  case /* Top */4 :
                      tmp = "left top";
                      break;
                  
                }
                break;
            case /* Right */3 :
                switch (pos2) {
                  case /* Bottom */0 :
                      tmp = "right bottom";
                      break;
                  case /* Center */1 :
                      tmp = "right center";
                      break;
                  case /* Left */2 :
                  case /* Right */3 :
                      tmp = "center center";
                      break;
                  case /* Top */4 :
                      tmp = "right top";
                      break;
                  
                }
                break;
            case /* Bottom */0 :
            case /* Top */4 :
                tmp = "center center";
                break;
            
          }
          break;
      case /* PositionExact */1 :
          var x = getLength(opt[0]);
          var y = getLength(opt[1]);
          tmp = "" + (String(x) + (" " + (String(y) + "")));
          break;
      case /* Unsafe_set */2 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "background-position",
          tmp
        ];
}

function backgroundRepeat(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Repeat */0 :
          tmp = "repeat";
          break;
      case /* RepeatX */1 :
          tmp = "repeat-x";
          break;
      case /* RepeatY */2 :
          tmp = "repeat-y";
          break;
      case /* NoRepeat */3 :
          tmp = "no-repeat";
          break;
      case /* Space */4 :
          tmp = "space";
          break;
      case /* Round */5 :
          tmp = "round";
          break;
      case /* Initial */6 :
          tmp = initial;
          break;
      case /* Inherit */7 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "background-repeat",
          tmp
        ];
}

function backgroundSize(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Auto */0 :
          tmp = auto;
          break;
      case /* Cover */1 :
          tmp = "cover";
          break;
      case /* Contain */2 :
          tmp = "contain";
          break;
      case /* Initial */3 :
          tmp = initial;
          break;
      case /* Inherit */4 :
          tmp = inherit_;
          break;
      
    }
  } else {
    switch (opt.tag | 0) {
      case /* Length */0 :
          var x = getLength(opt[0]);
          var y = getLength(opt[1]);
          tmp = "" + (String(x) + (" " + (String(y) + "")));
          break;
      case /* LengthX */1 :
          var x$1 = getLength(opt[0]);
          tmp = "" + (String(x$1) + "");
          break;
      case /* LengthY */2 :
          var y$1 = getLength(opt[0]);
          tmp = "auto " + (String(y$1) + "");
          break;
      case /* Unsafe_set */3 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "background-size",
          tmp
        ];
}

function background(opt) {
  return /* tuple */[
          "background",
          opt[0]
        ];
}

var Background = {
  backgroundAttachment: backgroundAttachment,
  backgroundBlendMode: backgroundBlendMode,
  _backgroundBoxing: _backgroundBoxing,
  backgroundClip: backgroundClip,
  backgroundColor: backgroundColor,
  backgroundImage: backgroundImage,
  backgroundOrigin: backgroundOrigin,
  backgroundPosition: backgroundPosition,
  backgroundRepeat: backgroundRepeat,
  backgroundSize: backgroundSize,
  background: background
};

function getBorderWidth(opt) {
  if (typeof opt !== "number") {
    if (opt.tag) {
      return opt[0];
    } else {
      return getLength(opt[0]);
    }
  }
  switch (opt) {
    case /* Medium */0 :
        return "medium";
    case /* Thin */1 :
        return "thin";
    case /* Thick */2 :
        return "thick";
    case /* Initial */3 :
        return initial;
    case /* Inherit */4 :
        return inherit_;
    
  }
}

function getBorderStyle(opt) {
  if (typeof opt !== "number") {
    return opt[0];
  }
  switch (opt) {
    case /* None */0 :
        return none;
    case /* Hidden */1 :
        return "hidden";
    case /* Dotted */2 :
        return "dotted";
    case /* Dashed */3 :
        return "dashed";
    case /* Solid */4 :
        return "solid";
    case /* Double */5 :
        return "double";
    case /* Groove */6 :
        return "groove";
    case /* Ridge */7 :
        return "ridge";
    case /* Inset */8 :
        return "inset";
    case /* Outset */9 :
        return "outset";
    case /* Initial */10 :
        return initial;
    case /* Inherit */11 :
        return inherit_;
    
  }
}

function getBorderColor(opt) {
  if (typeof opt !== "number") {
    return opt[0];
  }
  switch (opt) {
    case /* Transparent */0 :
        return "transparent";
    case /* Initial */1 :
        return initial;
    case /* Inherit */2 :
        return inherit_;
    
  }
}

function getBorder(widthOpt, styleOpt, colorOpt, param) {
  var width = widthOpt !== undefined ? widthOpt : /* Unsafe_set */Block.__(1, [""]);
  var style = styleOpt !== undefined ? styleOpt : /* Unsafe_set */[""];
  var color = colorOpt !== undefined ? colorOpt : /* Unsafe_set */Block.__(1, [""]);
  var width$1 = getBorderWidth(width);
  var style$1 = getBorderStyle(style);
  var color$1 = getBorderColor(color);
  return $$String.trim("" + (String(width$1) + (" " + (String(style$1) + (" " + (String(color$1) + ""))))));
}

function borderBottomWidth(opt) {
  return /* tuple */[
          "border-bottom-width",
          getBorderWidth(opt)
        ];
}

function borderBottomeStyle(opt) {
  return /* tuple */[
          "border-bottom-style",
          getBorderStyle(opt)
        ];
}

function borderBottomColor(opt) {
  return /* tuple */[
          "border-bottom-color",
          getBorderColor(opt)
        ];
}

function borderBottom(width, style, color, param) {
  return /* tuple */[
          "border-bottom",
          getBorder(width, style, color, undefined)
        ];
}

function getBorderRadius(radius) {
  if (typeof radius === "number") {
    if (radius === /* Initial */0) {
      return initial;
    } else {
      return inherit_;
    }
  } else if (radius.tag) {
    return radius[0];
  } else {
    return getLength(radius[0]);
  }
}

function borderBottomLeftRadius(opt) {
  return /* tuple */[
          "border-bottom-left-radius",
          getBorderRadius(opt)
        ];
}

function borderBottomRightRadius(opt) {
  return /* tuple */[
          "border-bottom-right-radius",
          getBorderRadius(opt)
        ];
}

function borderCollapse(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Separate */0 :
          tmp = "separate";
          break;
      case /* Collapse */1 :
          tmp = "collapse";
          break;
      case /* Initial */2 :
          tmp = initial;
          break;
      case /* Inherit */3 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "border-collapse",
          tmp
        ];
}

function borderColor(opt) {
  return /* tuple */[
          "border-color",
          getBorderColor(opt)
        ];
}

function borderImageSource(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* None */0 :
          tmp = "none";
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "border-image-source",
          tmp
        ];
}

function borderImageSlice(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Fill */0 :
          tmp = "fill";
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    switch (opt.tag | 0) {
      case /* Number */0 :
          tmp = "" + (String(opt[0]) + (" " + (String(opt[1]) + "")));
          break;
      case /* Pct */1 :
          tmp = "" + (String(opt[0]) + ("% " + (String(opt[1]) + "%")));
          break;
      case /* Unsafe_set */2 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "border-image-slice",
          tmp
        ];
}

function borderImageWidth(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Auto */0 :
          tmp = auto;
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    switch (opt.tag | 0) {
      case /* Length */0 :
          tmp = getLength(opt[0]);
          break;
      case /* Number */1 :
          tmp = String(opt[0]);
          break;
      case /* Pct */2 :
          tmp = String(opt[0]) + "%";
          break;
      case /* Unsafe_set */3 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "border-image-width",
          tmp
        ];
}

function borderImageOutset(opt) {
  var tmp;
  if (typeof opt === "number") {
    tmp = opt === /* Initial */0 ? initial : inherit_;
  } else {
    switch (opt.tag | 0) {
      case /* Length */0 :
          tmp = getLength(opt[0]);
          break;
      case /* Number */1 :
          tmp = String(opt[0]);
          break;
      case /* Unsafe_set */2 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "border-image-outset",
          tmp
        ];
}

function borderImageRepeat(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Stretch */0 :
          tmp = "stretch";
          break;
      case /* Repeat */1 :
          tmp = "repeat";
          break;
      case /* Round */2 :
          tmp = "round";
          break;
      case /* Space */3 :
          tmp = "space";
          break;
      case /* Initial */4 :
          tmp = initial;
          break;
      case /* Inherit */5 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "border-image-repeat",
          tmp
        ];
}

function borderImage(sourceOpt, sliceOpt, widthOpt, outsetOpt, repeatOpt, param) {
  var source = sourceOpt !== undefined ? sourceOpt : /* Unsafe_set */Block.__(1, [""]);
  var slice = sliceOpt !== undefined ? sliceOpt : /* Unsafe_set */Block.__(2, [""]);
  var width = widthOpt !== undefined ? widthOpt : /* Unsafe_set */Block.__(3, [""]);
  var outset = outsetOpt !== undefined ? outsetOpt : /* Unsafe_set */Block.__(2, [""]);
  var repeat = repeatOpt !== undefined ? repeatOpt : /* Unsafe_set */[""];
  var match = borderImageSource(source);
  var match$1 = borderImageSlice(slice);
  var match$2 = borderImageWidth(width);
  var match$3 = borderImageOutset(outset);
  var match$4 = borderImageRepeat(repeat);
  return /* tuple */[
          "border-image",
          $$String.trim("" + (String(match[1]) + (" " + (String(match$1[1]) + (" " + (String(match$2[1]) + (" " + (String(match$3[1]) + (" " + (String(match$4[1]) + ""))))))))))
        ];
}

function borderLeft(width, style, color, param) {
  return /* tuple */[
          "border-left",
          getBorder(width, style, color, undefined)
        ];
}

function borderLeftColor(opt) {
  return /* tuple */[
          "border-left-color",
          getBorderColor(opt)
        ];
}

function borderLeftStyle(opt) {
  return /* tuple */[
          "border-left-style",
          getBorderStyle(opt)
        ];
}

function borderLeftWidth(opt) {
  return /* tuple */[
          "border-left-width",
          getBorderWidth(opt)
        ];
}

function borderRadius(optList) {
  var radius = $$Array.of_list(List.map(getBorderRadius, optList)).join(" ");
  return /* tuple */[
          "border-radius",
          radius
        ];
}

function borderRight(width, style, color, param) {
  return /* tuple */[
          "border-right",
          getBorder(width, style, color, undefined)
        ];
}

function borderRightColor(opt) {
  return /* tuple */[
          "border-right-color",
          getBorderColor(opt)
        ];
}

function borderRightStyle(opt) {
  return /* tuple */[
          "border-right-style",
          getBorderStyle(opt)
        ];
}

function borderRightWidth(opt) {
  return /* tuple */[
          "border-right-width",
          getBorderWidth(opt)
        ];
}

function borderSpacing(opt) {
  var tmp;
  tmp = typeof opt === "number" ? (
      opt === /* Initial */0 ? initial : inherit_
    ) : (
      opt.tag ? opt[0] : $$Array.of_list(List.map(getLength, opt[0])).join(" ")
    );
  return /* tuple */[
          "border-spacing",
          tmp
        ];
}

function borderStyle(opt) {
  return /* tuple */[
          "border-style",
          getBorderStyle(opt)
        ];
}

function borderTop(width, style, color, param) {
  return /* tuple */[
          "border-top",
          getBorder(width, style, color, undefined)
        ];
}

function borderTopColor(opt) {
  return /* tuple */[
          "border-top-color",
          getBorderColor(opt)
        ];
}

function borderTopLeftRadius(opt) {
  return /* tuple */[
          "border-top-left-radius",
          getBorderRadius(opt)
        ];
}

function borderTopRightRadius(opt) {
  return /* tuple */[
          "border-top-right-radius",
          getBorderRadius(opt)
        ];
}

function borderTopStyle(opt) {
  return /* tuple */[
          "border-top-style",
          getBorderStyle(opt)
        ];
}

function borderTopWidth(opt) {
  return /* tuple */[
          "border-top-width",
          getBorderWidth(opt)
        ];
}

function borderWidth(opt) {
  return /* tuple */[
          "border-width",
          getBorderWidth(opt)
        ];
}

function border(width, style, color, param) {
  return /* tuple */[
          "border",
          getBorder(width, style, color, undefined)
        ];
}

var Border = {
  getBorderWidth: getBorderWidth,
  getBorderStyle: getBorderStyle,
  getBorderColor: getBorderColor,
  getBorder: getBorder,
  borderBottomWidth: borderBottomWidth,
  borderBottomeStyle: borderBottomeStyle,
  borderBottomColor: borderBottomColor,
  borderBottom: borderBottom,
  getBorderRadius: getBorderRadius,
  borderBottomLeftRadius: borderBottomLeftRadius,
  borderBottomRightRadius: borderBottomRightRadius,
  borderCollapse: borderCollapse,
  borderColor: borderColor,
  borderImageSource: borderImageSource,
  borderImageSlice: borderImageSlice,
  borderImageWidth: borderImageWidth,
  borderImageOutset: borderImageOutset,
  borderImageRepeat: borderImageRepeat,
  borderImage: borderImage,
  borderLeft: borderLeft,
  borderLeftColor: borderLeftColor,
  borderLeftStyle: borderLeftStyle,
  borderLeftWidth: borderLeftWidth,
  borderRadius: borderRadius,
  borderRight: borderRight,
  borderRightColor: borderRightColor,
  borderRightStyle: borderRightStyle,
  borderRightWidth: borderRightWidth,
  borderSpacing: borderSpacing,
  borderStyle: borderStyle,
  borderTop: borderTop,
  borderTopColor: borderTopColor,
  borderTopLeftRadius: borderTopLeftRadius,
  borderTopRightRadius: borderTopRightRadius,
  borderTopStyle: borderTopStyle,
  borderTopWidth: borderTopWidth,
  borderWidth: borderWidth,
  border: border
};

function bottom(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Auto */0 :
          tmp = auto;
          break;
      case /* Initial */1 :
          tmp = initial;
          break;
      case /* Inherit */2 :
          tmp = inherit_;
          break;
      
    }
  } else {
    switch (opt.tag | 0) {
      case /* Length */0 :
          tmp = getLength(opt[0]);
          break;
      case /* Pct */1 :
          tmp = String(opt[0]) + "%";
          break;
      case /* Unsafe_set */2 :
          tmp = opt[0];
          break;
      
    }
  }
  return /* tuple */[
          "bottom",
          tmp
        ];
}

var Bottom = {
  bottom: bottom
};

function boxDecorationBreak(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Slice */0 :
          tmp = "slice";
          break;
      case /* Clone */1 :
          tmp = "clone";
          break;
      case /* Initial */2 :
          tmp = initial;
          break;
      case /* Inherit */3 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "box-decoration-break",
          tmp
        ];
}

function boxShadow(shadowList) {
  return /* tuple */[
          "box-shadow",
          $$Array.of_list(shadowList).join(" ")
        ];
}

function boxSizing(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* ContentBox */0 :
          tmp = "content-box";
          break;
      case /* BorderBox */1 :
          tmp = "border-box";
          break;
      case /* Initial */2 :
          tmp = initial;
          break;
      case /* Inherit */3 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "box-sizing",
          tmp
        ];
}

var Box = {
  boxDecorationBreak: boxDecorationBreak,
  boxShadow: boxShadow,
  boxSizing: boxSizing
};

function getBreak(opt) {
  if (typeof opt !== "number") {
    return opt[0];
  }
  switch (opt) {
    case /* Auto */0 :
        return auto;
    case /* All */1 :
        return "all";
    case /* Always */2 :
        return "always";
    case /* Avoid */3 :
        return "avoid";
    case /* AvoidColumn */4 :
        return "avoid-column";
    case /* AvoidPage */5 :
        return "avoid-page";
    case /* AvoidRegion */6 :
        return "avoid-region";
    case /* Column */7 :
        return "column";
    case /* Left */8 :
        return "left";
    case /* Page */9 :
        return "page";
    case /* Recto */10 :
        return "recto";
    case /* Region */11 :
        return "region";
    case /* Right */12 :
        return "right";
    case /* Verso */13 :
        return "verso";
    case /* Initial */14 :
        return initial;
    case /* Inherit */15 :
        return inherit_;
    
  }
}

function breakAfter(opt) {
  return /* tuple */[
          "break-after",
          getBreak(opt)
        ];
}

function breakBefore(opt) {
  return /* tuple */[
          "break-before",
          getBreak(opt)
        ];
}

function breakInside(opt) {
  var tmp;
  if (typeof opt === "number") {
    switch (opt) {
      case /* Auto */0 :
          tmp = auto;
          break;
      case /* Avoid */1 :
          tmp = "avoid";
          break;
      case /* AvoidColumn */2 :
          tmp = "avoid-column";
          break;
      case /* AvoidPage */3 :
          tmp = "avoid-page";
          break;
      case /* AvoidRegion */4 :
          tmp = "avoid-region";
          break;
      case /* Initial */5 :
          tmp = initial;
          break;
      case /* Inherit */6 :
          tmp = inherit_;
          break;
      
    }
  } else {
    tmp = opt[0];
  }
  return /* tuple */[
          "break-inside",
          tmp
        ];
}

var Break = {
  getBreak: getBreak,
  breakAfter: breakAfter,
  breakBefore: breakBefore,
  breakInside: breakInside
};

var $$class = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class);

var captionSide = CamlinternalOO.create_object_opt(undefined, $$class);

var $$class$1 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$1);

var caretColor = CamlinternalOO.create_object_opt(undefined, $$class$1);

var $$class$2 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$2);

var charset = CamlinternalOO.create_object_opt(undefined, $$class$2);

var $$class$3 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$3);

var clear = CamlinternalOO.create_object_opt(undefined, $$class$3);

var $$class$4 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$4);

var clip = CamlinternalOO.create_object_opt(undefined, $$class$4);

var $$class$5 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$5);

var color = CamlinternalOO.create_object_opt(undefined, $$class$5);

var $$class$6 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$6);

var columnCount = CamlinternalOO.create_object_opt(undefined, $$class$6);

var $$class$7 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$7);

var columnFill = CamlinternalOO.create_object_opt(undefined, $$class$7);

var $$class$8 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$8);

var columnGap = CamlinternalOO.create_object_opt(undefined, $$class$8);

var $$class$9 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$9);

var columnRule = CamlinternalOO.create_object_opt(undefined, $$class$9);

var $$class$10 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$10);

var columnRuleColor = CamlinternalOO.create_object_opt(undefined, $$class$10);

var $$class$11 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$11);

var columnRuleStyle = CamlinternalOO.create_object_opt(undefined, $$class$11);

var $$class$12 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$12);

var columnRuleWidth = CamlinternalOO.create_object_opt(undefined, $$class$12);

var $$class$13 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$13);

var columnSpan = CamlinternalOO.create_object_opt(undefined, $$class$13);

var $$class$14 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$14);

var columnWidth = CamlinternalOO.create_object_opt(undefined, $$class$14);

var $$class$15 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$15);

var columns = CamlinternalOO.create_object_opt(undefined, $$class$15);

var $$class$16 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$16);

var content = CamlinternalOO.create_object_opt(undefined, $$class$16);

var $$class$17 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$17);

var counterIncrement = CamlinternalOO.create_object_opt(undefined, $$class$17);

var $$class$18 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$18);

var counterReset = CamlinternalOO.create_object_opt(undefined, $$class$18);

var $$class$19 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$19);

var cursor = CamlinternalOO.create_object_opt(undefined, $$class$19);

var $$class$20 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$20);

var direction = CamlinternalOO.create_object_opt(undefined, $$class$20);

var $$class$21 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$21);

var display = CamlinternalOO.create_object_opt(undefined, $$class$21);

var $$class$22 = CamlinternalOO.create_table(0);

CamlinternalOO.init_class($$class$22);

var emptyCells = CamlinternalOO.create_object_opt(undefined, $$class$22);

var hidden = "hidden";

var flex = "flex";

var column = "column";

var flexEnd = "flexEnd";

var forwards = "forwards";

var center = "center";

var underline = "underline";

var borderBottomStyle = borderBottomeStyle;

export {
  clsx ,
  toFloat ,
  toInt ,
  toStr ,
  vw ,
  vh ,
  px ,
  pct ,
  deg ,
  ms ,
  width ,
  height ,
  overflow ,
  flexDirection ,
  padding ,
  transition ,
  transform ,
  zIndex ,
  margin ,
  opacity ,
  textAlign ,
  lineHeight ,
  fontSize ,
  textDecoration ,
  nthChild ,
  $$var ,
  hover ,
  hidden ,
  flex ,
  column ,
  flexEnd ,
  rotate ,
  translateY ,
  translate ,
  important ,
  forwards ,
  center ,
  underline ,
  keyframes ,
  css ,
  create ,
  getClassName ,
  useStyles ,
  makeGlobalStyles ,
  makeStyles ,
  makeThemeStyles ,
  auto ,
  initial ,
  inherit_ ,
  none ,
  unset ,
  Length ,
  TimingFunctions ,
  Align ,
  All ,
  Animation ,
  alignContent ,
  alignItems ,
  alignSelf ,
  all ,
  animation ,
  animationDelay ,
  animationDirection ,
  animationDuration ,
  animationFillMode ,
  animationIterationCount ,
  animationName ,
  animationPlayState ,
  animationTimingFunction ,
  Backface ,
  backfaceVisibilty ,
  Background ,
  background ,
  backgroundAttachment ,
  backgroundBlendMode ,
  backgroundClip ,
  backgroundColor ,
  backgroundImage ,
  backgroundOrigin ,
  backgroundPosition ,
  backgroundRepeat ,
  backgroundSize ,
  Border ,
  border ,
  borderBottom ,
  borderBottomColor ,
  borderBottomLeftRadius ,
  borderBottomRightRadius ,
  borderBottomStyle ,
  borderBottomWidth ,
  borderCollapse ,
  borderColor ,
  borderImage ,
  borderImageOutset ,
  borderImageRepeat ,
  borderImageSlice ,
  borderImageSource ,
  borderImageWidth ,
  borderLeft ,
  borderLeftColor ,
  borderLeftStyle ,
  borderLeftWidth ,
  borderRadius ,
  borderRight ,
  borderRightColor ,
  borderRightStyle ,
  borderRightWidth ,
  borderSpacing ,
  borderStyle ,
  borderTop ,
  borderTopColor ,
  borderTopLeftRadius ,
  borderTopRightRadius ,
  borderTopStyle ,
  borderTopWidth ,
  borderWidth ,
  Bottom ,
  bottom ,
  Box ,
  boxDecorationBreak ,
  boxShadow ,
  boxSizing ,
  Break ,
  breakAfter ,
  breakBefore ,
  breakInside ,
  captionSide ,
  caretColor ,
  charset ,
  clear ,
  clip ,
  color ,
  columnCount ,
  columnFill ,
  columnGap ,
  columnRule ,
  columnRuleColor ,
  columnRuleStyle ,
  columnRuleWidth ,
  columnSpan ,
  columnWidth ,
  columns ,
  content ,
  counterIncrement ,
  counterReset ,
  cursor ,
  direction ,
  display ,
  emptyCells ,
  
}
/* class Not a pure module */
