// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Mui from "./Mui.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";

var themeProviderGlobalStyles = {
  "@global": {
    body: {
      overflow: "hidden"
    }
  }
};

var useThemeProviderStyles = Styles.makeStyles(themeProviderGlobalStyles);

function ThemeProvider$ThemeProvider(Props) {
  var children = Props.children;
  Curry._1(useThemeProviderStyles, undefined);
  return React.createElement(Core.CssBaseline, {
              children: React.createElement(Core.ThemeProvider, {
                    children: children,
                    theme: Mui.Theme.theme
                  })
            });
}

var ThemeProvider = {
  make: ThemeProvider$ThemeProvider
};

export {
  themeProviderGlobalStyles ,
  useThemeProviderStyles ,
  ThemeProvider ,
  
}
/* useThemeProviderStyles Not a pure module */
